spring:
  application:
    name: backend
  ai:
    stabilityai:
      api-key: ${STABILITY_API_KEY}
    zhipuai:
      api-key: ${ZHIPU_API_KEY}
    togetherai:
      api-key: ${TOGETHER_API_KEY}
aws:
  s3:
    secret:
      access:
        key: ${AWS_S3_SECRET_ACCESS_KEY}
    access:
      key:
       id: ${AWS_S3_ACCESS_KEY_ID}
    region: ${AWS_S3_REGION}
    bucket:
      name: ${AWS_S3_BUCKET_NAME}